on: push

name: UI

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Env
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Test Unit
        run: |
          just deps
          just test-ui
